### PR TITLE
Implement drag and drop

### PR DESCRIPTION
**Pull request by idbrii**
Support dragging scenes into the scene editor to spawn them.

### CODE REVIEW

**Comment by Frontrider** [comment]
Yeah, that is something I wanted to do, but really don't know how I'd do.

**Comment by idbrii** [comment]
It works really well! Once I figured out what you have to return from get_drag_data for the scene editor to understand, it was easy.

**Comment by Frontrider** [comment]
Yeah, that does exactly what it needs to.

Can you explain what is happening here? The `Scene` just implements whatever this `get_drag_data` needs, and that is why it just works?

**Comment by idbrii** [comment]
Yeah, godot's drag and drop us just a Control uses get_drag_data and when you drag over another control (like the scene) that gets is_drag_allowed (or something) called so it can checks if it knows what to do with the data we set in get_drag_data. Then there's another callback for when you actually release. Not sure how the spawn happens right away, so maybe I don't entirely understand.

Once I figured out how the scene editor's drop format (that dict with file paths), then it worked.

More details in my answer to myself: https://godotengine.org/qa/144475/how-can-implement-drag-and-drop-into-scene-from-editorplugin?show=144475#q144475

**Comment by Frontrider** [comment]
It even drops to the expected part of the scene tree (currently selected node), so it is consistent with everything else I did.

**Pull request merged**
